version: 2.1

jobs:
  build:
    docker:
      - image: weaveworks/eksctl
    steps:
      - checkout
      - run: eksctl create cluster --name capstone-kuber-prod --region=us-east-1
  test:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test
