version: 2.1

jobs:
  build-test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            make install
      - run:
          name: Lint Dockerfile
          command: |
            make lint-docker
      - run:
          name: Lint index.html
          command: |
            make lint-html

  deploy-cluster:
    docker:
      - image: weaveworks/eksctl
    steps:
      - checkout
      - run:
          name: Check EKS prod cluster and run if not running
          command: |
            set +e
            eksctl get cluster --name=capstone-kuber-prod --region=us-east-1 > /tmp/cluster_status 2>&1
            if grep -q "No cluster found for name" /tmp/cluster_status; then
              echo "Cluster not found, starting prod cluster"
              eksctl create cluster --name capstone-kuber-prod --ssh-access --ssh-public-key=iamin --region=us-east-1
            elif grep -q "ACTIVE" /tmp/cluster_status; then
              echo "Cluster is running"
            else
              echo "Unknown cluster status"
              exit 1
            fi
            eksctl utils write-kubeconfig --cluster=capstone-kuber-prod --kubeconfig=manifest.yaml
            pwd
            ls ~/project/ -lah
      - persist_to_workspace:
          root: ~/project/
          paths:
            - manifest.yaml

  build-docker:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: |
            docker build -t my-nginx-hello-world .
      - run:
          name: Push Docker image to registry
          command: |
            docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
            docker tag my-nginx-hello-world "$DOCKER_USERNAME/my-nginx-hello-world"
            docker push "$DOCKER_USERNAME/my-nginx-hello-world"

  deploy-docker:
    docker:
      - image: weaveworks/eksctl
    steps:
      - attach_workspace:
          at: ~/project/
      - run:
          name: Deploy Docker image to EKS
          command: |
            ls
            kubectl apply -f manifest.yaml
            kubectl set image deployment/my-nginx-hello-world nginx="$DOCKER_USERNAME/my-nginx-hello-world"
            kubectl rollout status deployment/my-nginx-hello-world

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - deploy-cluster
      - build-test
      - build-docker
      - deploy-docker